backend:
  name: github
  repo: Protonull/Wesbury
  branch: main

media_folder: "static/uploads/"
public_folder: "/uploads/"

collections:
  #######################################################
  ## Constitution
  #######################################################
  - name: "constitution"
    label: "Constitution"
    folder: "src/pages/admiralty/constitution/"
    create: true
    slug: "{{identifier}}"
    extension: "mdx"
    format: "yaml-frontmatter"
    editor:
      preview: false
    sortable_fields: ["order"]
    filter: { field: "template", value: "legislation" }
    fields:
      - label: "Template"
        name: "type"
        widget: "hidden"
        required: true
        default: "legislation"
      - label: "Identifier"
        name: "identifier"
        widget: "string"
        required: true
        pattern: ["^[a-z0-9]+(?:_[a-z0-9]+)*$", "Must be a valid slug! e.g: bill_of_rights"]
        hint: "This identifies the law and so should reflect the purpose of the law, e.g: bill_of_rights"
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
        hint: "The name of the piece of legislation, e.g: Bill of Rights"
      - label: "Category"
        name: "category"
        widget: "select"
        required: true
        hint: "The type of law this legislation is classed as."
        options: ["STANDING ORDER", "CONSTITUTION", "TREATY", "PRECEDENT"]
      - label: "Order of Importance"
        name: "order"
        widget: "number"
        required: true
        hint: "Lower means more important."
        value_type: "int"
        step: 1
        default: 1000
      - label: "Content"
        name: "body"
        widget: "markdown"
        hint: "You do not need to include the title in the body."
